<div class="container">
<div class="col-lg-12 col-md-12 col-sm-12">
<Body style="background-color:#ffffe6">
<h1 style="margin-top:70px">Legal</h1>
<br>
<h2>Introduction</h2>
<p style="font-family:Comic Sans MS">The following terms are a legal agreement between you, your employees, agents, contractors and any other entity on whose behalf you accept these terms (collectively "You" or "Your"), and Junction Software Pvt Ltd. By accessing, browsing, or using any Junction Software-provided website, ("Website"), You acknowledge that You have read, understood, and agree to be bound by these terms and to comply with all applicable laws and regulations, including export and re-export control laws and regulations. Website shall not include any site used to provide the Junction Software on-demand Software as a service delivery. If You do not agree to these terms, You may not use this Website. This Website may contain a variety of resources including, but not limited to, documentation and other Junction Software-provided product information (collectively the "Documentation"), download areas, communication forums, and other services (collectively "Services"), software, including developer tools and sample code (collectively "Software"), and Web Service Application Program Interface information ("APIs"). Your use of any Documentation, Services, Software, and Web Service APIs, is subject to, and specifically conditioned upon Your acceptance of the following Terms and Conditions ("Terms"). Junction Software reserves the right to update the Terms at any time without notice to You. Unless explicitly stated herein, nothing in these Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication, or otherwise.</p>

<br>
<h2>Accounts</h2>
<p style="font-family:Comic Sans MS">During the registration process, You agree that any information provided shall be current, complete and accurate as prompted by the applicable registration form. You agree that any registration information You give to Junction Software will always be accurate, correct and up to date. You agree and understand that You are responsible for maintaining the confidentiality of passwords associated with any account You use to access any portion of the Website. Accordingly, You agree that You will be solely responsible to Junction Software for all activities that occur under Your account. You agree to notify Junction Software immediately of any unauthorized use of Your account or any other breach of security. You may be allowed to choose an alias and a representative image during the registration process. You may not use an alias or image that is in use by someone else, impersonates another person, violates the intellectual property rights of any third party, is deemed vulgar or otherwise offensive or inappropriate by Junction Software in its sole discretion. The information You provide to Junction Software during the registration process will be governed by the terms of Junction Software's current privacy policy. Junction Software Privacy Policy</p>
<br>
<p style="font-family:Comic Sans MS">You are entirely responsible for all material including, but not limited to, software code, articles, feedback or suggestions, ("Content") that You upload, post or otherwise transmit via the Website. You agree not to upload, post or otherwise transmit via the Website Content that: (a) is inaccurate, harmful, obscene, pornographic, defamatory, racist, violent, offensive, harassing, or otherwise objectionable to Junction Software in its sole discretion or to other users of the Website; (b) includes unauthorized disclosure of personal information or other confidential information; (c) violates or infringes any third party intellectual property rights; or (d) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment. You agree that You will not use the Website to: (a) transmit spam, bulk or unsolicited communications; (b) pretend to be Junction Software or someone else, or spoof Junction Software's or someone else's identity; (c) forge headers or otherwise manipulate identifiers (including URLs) in order to disguise the origin of any Content transmitted through the Services; (d) misrepresent Your affiliation with a person or entity; (e) disrupt the normal flow of dialogue or otherwise act in a manner that negatively affects other users' ability to use the Website; (f) engage in activities that would violate any fiduciary relationship, any applicable local, state, national or international law, or any regulations having the force of law, including but not limited to attempting to compromise the security of any networked account or site, stalking, or making threats of harm; or (g) collect or store personal data about other users unless specifically authorized by such users. By posting Content to the Website, You warrant that You own or otherwise possess all intellectual property and other rights necessary to post such Content on the Website and to permit others to make use of Your Content. Junction Software reserves the right to edit or remove Content that violates these Terms or that contains third-party commercial advertisements.</p>

<br>
<h2>Submissions</h2>
<p style="font-family:Comic Sans MS">You retain copyright You already hold in Content which You submit, post or display on or through, the Services. By submitting, posting or displaying the Content You give Junction Software and its affiliated companies, sublicensees (including third parties whose products, technologies and services use or interface with any specific parts of a Junction Software software or service that includes the Content) and other Users of the Website, a perpetual, irrevocable, transferable, worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute any Content which You submit, post or display on or through, the Website. You will not provide any Content that is subject to a license that requires Junction Software to license its software or documentation to third parties because we include Your Content in them.</p>

<br>
<p style="font-family:Comic Sans MS">Junction Software is under no obligation to post or use any Content You may provide, and Junction Software may remove any Content at any time in its sole discretion. By Posting Content You warrant and represent that You have all the rights, power and authority necessary to grant the above licensee.</p>
<br>

<h2>Software</h2>
<p style="font-family:Comic Sans MS">All Software which may be available to be downloaded from the Website (the "Software") is the copyrighted work of Junction Software and/or third party providers. Use of the Software is governed by the terms of any license agreement accompanying the Software (the "License Agreement"). If Junction Software makes Software available on this Website without a License Agreement, You may use such Software according to the following terms and conditions: THE SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR SIMILAR DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THE SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. SUBJECT TO THE FOREGOING, THE SOFTWARE MAY BE FREELY REPRODUCED, DISTRIBUTED, TRANSMITTED, USED, MODIFIED, BUILT UPON, OR OTHERWISE EXPLOITED BY OR ON BEHALF OF JUNCTION SOFTWARE OR ITS AFFILIATES, ANY CUSTOMER OR PARTNER OF JUNCTION SOFTWARE OR ITS AFFILIATES, OR ANY DEVELOPER OF APPLICATIONS THAT INTERFACE WITH THE JUNCTION SOFTWARE SERVICE, FOR ANY PURPOSE RELATED TO USE OF THE SOFTWARE. Any reproduction or redistribution of the Software not in accordance with the License Agreement or these Terms is expressly prohibited.</p>
<br>

<h2>Documentation</h2>
<p style="font-family:Comic Sans MS">All Documentation contained on or accessed via the Website is the copyrighted work of Junction Software and/or its suppliers. Use of the Documentation is governed by the terms of the Master Agreement, if any, between You and Junction Software ("Master Agreement"). If Documentation is made available to You on this Website without a Master Agreement, then You may annotate, translate, and make a reasonable number of copies of the Junction Software documentation for Your internal use in designing, developing, and testing Your software provided that: (a) any copyright notice pertaining to the Documentation remains, and a permission notice (e.g., "Used with permission") is added to such Documentation. You may not publish any such annotations or translations. You must preserve any copyright notice in all copies of the Documentation. No logo, graphic, or image from the Website may be copied or retransmitted unless expressly permitted by Junction Software. Use for any other purpose is expressly prohibited. Documentation does not include the design or layout of the Website or any other Junction Software site.</p>



<br>
<h2>Junction Software Web Service API</h2>
<p style="font-family:Comic Sans MS">Junction Software hereby grants You a non-exclusive, non-sub licensable, non-transferable limited use license to internally use the Junction Software Web Service APIs as made available via the Website. Use of the APIs is limited to internal use for the sole purpose of development of software interfaces that enable access to data between Your developed product, third party products, and Junction Software. You assume all liability as a result of any use of the APIs. This license does not grant You rights to any version enhancement or availability of the APIs, or to support of any kind while using the Website. Junction Software may revise or cease to provide the APIs without notice at any time in Junction Software's sole discretion.</p>
<br>
<p style="font-family:Comic Sans MS">WITHOUT LIMITING THE FOREGOING, COPYING OR REPRODUCTION OF THE SOFTWARE AND/OR APIS TO ANY OTHER SERVER OR LOCATION FOR FURTHER REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PROHIBITED, UNLESS SUCH REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PERMITTED BY THE LICENSE AGREEMENT ACCOMPANYING SUCH SOFTWARE AND/OR APIS.</p>


<br>
<h2>Hyperlinks</h2>
<p style="font-family:Comic Sans MS">The WEBSITE may include links to other websites or content or resources. Junction Software may have no control over any websites or resources which are provided by companies or persons other than Junction Software. THIRD-PARTY SITES ARE NOT UNDER THE CONTROL OF JUNCTION SOFTWARE AND JUNCTION SOFTWARE IS NOT RESPONSIBLE FOR THE CONTENTS OF ANY LINKED SITE OR ANY LINK CONTAINED IN A LINKED SITE, OR ANY CHANGES OR UPDATES TO SUCH SITES. FURTHER, JUNCTION SOFTWARE IS NOT RESPONSIBLE FOR ANY CONTENT RECEIVED FROM ANY THIRD-PARTY SITE. JUNCTION SOFTWARE IS PROVIDING THESE LINKS TO YOU ONLY AS A CONVENIENCE, AND THE INCLUSION OF ANY LINK DOES NOT IMPLY JUNCTION SOFTWARE'S ENDORSEMENT OF THE SITE.</p>
<br>


<h2>Disclaimer of warranty</h2>
<p style="font-family:Comic Sans MS">USE OF THIS SITE IS AT YOUR SOLE RISK. ALL CONTENT, DOCUMENTATION, MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, AND SERVICES ARE PROVIDED "AS IS," WITH NO WARRANTIES OR GUARANTEES WHATSOEVER. JUNCTION SOFTWARE EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, STATUTORY, AND OTHER WARRANTIES, GUARANTEES, OR REPRESENTATIONS, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY AND INTELLECTUAL PROPERTY RIGHTS. WITHOUT LIMITATION, JUNCTION SOFTWARE MAKES NO WARRANTY OR GUARANTEE THAT THIS WEBSITE OR ANY CONTENT WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND AND AGREE THAT IF YOU DOWNLOAD OR OTHERWISE OBTAIN CONTENT, MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, OR SERVICES, YOU DO SO AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES THAT MAY RESULT, INCLUDING LOSS OF DATA OR DAMAGE TO YOUR COMPUTER SYSTEM. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.</p>

<br>
<h2>Limitation of liability</h2>
<p style="font-family:Comic Sans MS">IN NO EVENT WILL JUNCTION SOFTWARE BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY TYPE WHATSOEVER RELATED TO OR ARISING FROM THIS WEBSITE OR ANY USE OF THIS WEBSITE, OR OF ANY SITE OR RESOURCE LINKED TO, REFERENCED, OR ACCESSED THROUGH THIS WEBSITE, OR FOR THE USE OR DOWNLOADING OF, OR ACCESS TO, ANY MATERIALS, INFORMATION, PRODUCTS, OR SERVICES, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOST SAVINGS OR LOSS OF PROGRAMS OR OTHER DATA, EVEN IF JUNCTION SOFTWARE IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS EXCLUSION AND WAIVER OF LIABILITY APPLIES TO ALL CAUSES OF ACTION, WHETHER BASED ON CONTRACT, WARRANTY, TORT, OR ANY OTHER LEGAL THEORIES.</p>
<br>
<p>Additional or different terms, conditions, and notices may apply to specific materials, information, products, software, and services offered through this Website. In the event of any conflict, such additional or different terms, conditions, and notices will prevail over these Terms of Use. Please see the applicable agreement or notice.</p>

<br>
<h2>General</h2>
<p style="font-family:Comic Sans MS">The Terms constitute the whole legal agreement between You and Junction Software and govern Your use of the Website (but excluding any services which Junction Software may provide to You under a separate written agreement), and completely replace any prior agreements between You and Junction Software in relation to the Website. You agree that Junction Software may provide You with notices, including those regarding changes to the Terms, by email, regular mail, or postings on the Website. You agree that if Junction Software does not exercise or enforce any legal right or remedy which is contained in the Terms (or which Junction Software has the benefit of under any applicable law), this will not be taken to be a formal waiver of Junction Software's rights and that those rights or remedies will still be available to Junction Software.</p>
<br>
<p style="font-family:Comic Sans MS">If any court of law, having the jurisdiction to decide on this matter, rules that any provision of these Terms is invalid, then that provision will be removed from the Terms without affecting the rest of the Terms. The remaining provisions of the Terms will continue to be valid and enforceable.</p>

<br>
<p style="font-family:Comic Sans MS">You acknowledge and agree that all Junction Software affiliates shall be third party beneficiaries to the Terms and that such other companies shall be entitled to directly enforce, and rely upon, any provision of the Terms which confers a benefit on (or rights in favor of) them. Other than this, no other person or company shall be third party beneficiaries to the Terms.</p>
<br>
<p style="font-family:Comic Sans MS">The Terms, and Your relationship with Junction Software under the Terms, shall be governed by the laws of the India without regard to its conflict of laws provisions. You and Junction Software agree to submit to the exclusive jurisdiction of the courts located within the city of Bhopal , Madhya Pradesh to resolve any legal matter arising from the Terms. Notwithstanding this, You agree that Junction Software shall still be allowed to apply for injunctive remedies in any jurisdiction.</p>
<br>
<p style="font-family:Comic Sans MS">Junction Software reserves all rights not expressly granted under these Terms, and no other rights are granted under these Terms by implication or estoppel or otherwise.</p>

</div> 
</div> 